---
title: "Current Economic Outlook"
date: "`r paste0('updated: ',as.Date(file.info(here::here('processed_data','nested_dataframe.rds'))$mtime-lubridate::hours(7)))`"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    source_code: https://github.com/bcgov/current_economic_analysis
    css: style.css
runtime: shiny
resource_files:
- processed_data/mpi.rds
- processed_data/nested_dataframe.rds
- R/functions.R
---
  
```{r global, include=FALSE}
# Copyright 2022 Province of British Columbia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.
#libraries----------
#library(DT)
library(tidyverse)
library(tsibble) #data includes a tsibble::yearquarter field
library(lubridate) #years and months not exported by lubridate
library(ggthemes)
themes <- ls("package:ggplot2", pattern = "^theme_")
themes <- themes[themes != "theme_get" &
  themes != "theme_set" &
  themes != "theme_replace" &
  themes != "theme_test" &
  themes != "theme_update"]
themes <- c(themes, ls("package:ggthemes", pattern = "^theme_"))

#load objects----------
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
nested_dataframe <- readRDS(here::here("processed_data", "nested_dataframe.rds"))
mpi <- readRDS(here::here("processed_data", "mpi.rds"))%>%
  filter(last_update>today()-years(5)) # a single project had a last_update value of 2016?
#functions------------
#Extractor function (retrieve cell)---------- 
extract_cell <- function(df, nm){
  df <- df%>%
    filter(name==nm)%>%
    select(value)%>%
    pull()
  df<- df[[1]]
  return(df)
}
plotly_ts <- function(df, thing, format_as, tt_text, theme, type){
  plt <-  ggplot(df, aes(Month, 
                          {{  thing  }}, 
                          colour = Series,
                          fill = Series,
                          group = Series,
                          text = paste(
                            "\nIn", Month, tt_text, "\n", Series,   
                            "was", format_as({{ thing  }}, accuracy = .01))))+
            scale_colour_manual(values=cbPalette)+
            scale_fill_manual(values=cbPalette)+
            scale_y_continuous(label=format_as)+
            get(theme)()
  if(type=="column"){
    plt <- plt+
       geom_col(position = "dodge", size=0)
  }else{
    plt <- plt+
       geom_line() 
  }
  plotly::ggplotly(plt, tooltip="text")
}
```


Time Series:
=====================================  
 
 Inputs {.sidebar}
-------------------------------------

<br>

- This dashboard retrieves `r dim(nested_dataframe)[1]` time series pertinent to British Columbia's current economic outlook. 
- It also contains recent information on the [Major Project Inventory](https://richard-martin.shinyapps.io/Major_Project_Inventory/).
- The data is updated nightly.


```{r}
selectInput("name", 
            label = "Choose a data set:",
            choices = nested_dataframe$name, 
            selected = nested_dataframe$name[1])

selectInput(
        "theme",
        "Choose a plot theme:",
        themes,
        selected = "theme_minimal",
        multiple = FALSE
      )
selectInput(
        "type",
        "Choose a plot type:",
        c("line","column"),
        selected = "line",
        multiple = FALSE
      )

reactive_df <- reactive({
  extract_cell(nested_dataframe, input$name)
})
```

Column{.tabset}
-----------------------------------------------------------------------

### Levels:

#### 

```{r}
plotly::renderPlotly({plotly_ts(reactive_df(), 
                        Value, 
                        scales::comma,
                        "the level of ",
                        input$theme,
                        input$type
                        )})%>%
  bindCache(input$name, input$theme, input$type)
```

#### 

```{r}
renderText({
  paste("Source: ",reactive_df()$Source[1])
})
```

### Monthly Changes:

####

```{r}
plotly::renderPlotly({plotly_ts(reactive_df(),
                        `Monthly Change`, 
                        scales::percent,
                        "the monthly rate of change of ",
                        input$theme,
                        input$type)})%>%
  bindCache(input$name, input$theme, input$type)
```

#### 

```{r}
renderText({
  paste("Source: ",reactive_df()$Source[1])
})
```

### Annual Changes:

####

```{r}
plotly::renderPlotly({plotly_ts(reactive_df(), 
                        `Annual Change`, 
                        scales::percent,
                        "the annual rate of change of ",
                        input$theme,
                        input$type)})%>%
  bindCache(input$name, input$theme, input$type)
```

####

```{r}
renderText({
  paste("Source: ",reactive_df()$Source[1])
})
```

### The Data:

####
  
```{r}
DT::renderDataTable(server=FALSE,{
  reactive_df()%>%
    select(-Source)%>%
    mutate(Month=as.character(Month),
           `Monthly Change` = scales::percent(`Monthly Change`, accuracy=.1),
           `Annual Change` = scales::percent(`Annual Change`, accuracy=.1))%>%
    DT::datatable(extensions = "Buttons",
              rownames = FALSE,    
              options = list(columnDefs = list(list(className = 'dt-center', targets = "_all")),
                             paging = TRUE,
                             scrollX=TRUE,
                             scrollY=TRUE,
                             searching = TRUE,
                             ordering = TRUE,
                             dom = 'Btip',
                             buttons = list(
                                list(extend = 'csv', filename =  input$name),
                                list(extend = 'excel', filename = input$name)
                             ),
                             pageLength=10, 
                             lengthMenu=c(3,5)))
  })%>%
  bindCache(input$name)
```

####

```{r}
renderText({
  paste("Source: ",reactive_df()$Source[1])
})
```

Major Project Inventory: 
=====================================     

Inputs {.sidebar}
-------------------------------------

```{r}
char_cols <- colnames(mpi)[sapply(mpi,class)=="character"]
possible_vars <- char_cols[char_cols!="source"]

selectInput("filter_var", label = "Choose a quarter:",
            choices = unique(mpi$last_update), selected = tail(unique(mpi$last_update)))
selectInput("x_var", label = "Choose a variable for x axis:",
            choices = possible_vars, selected = "region")
selectInput("y_var", label = "Choose a variable for y axis:",
            choices = possible_vars, selected = "project_stage")
selectInput("facet_var", label = "Choose a variable to facet by:",
            choices = possible_vars, selected = "project_status")

observe({
  updateSelectInput(session, "y_var", choices= possible_vars[possible_vars!=input$x_var])
})
observe({
  updateSelectInput(session, "facet_var", choices= possible_vars[possible_vars!=input$x_var & possible_vars!=input$y_var])
})

mpi_group_summary <- reactive({
  mpi%>%
  filter(as.character(last_update) == as.character(input$filter_var))%>%
  group_by_(`X-axis variable`=input$x_var, #group_by_ DEPRECATED.
            `Y-axis variable`=input$y_var,
            `Facet variable`=input$facet_var)%>%
  summarize(`Total Cost (M)`=sum(estimated_cost, na.rm=TRUE))%>%
  filter(`Total Cost (M)`>0)
})
```

Column {.tabset}
-----------------------------------------------------------------------

### Plot:

```{r}

renderPlot({
  plt <- ggplot(mpi_group_summary(), aes(`X-axis variable`, 
                                      `Y-axis variable`, 
                                      fill=`Total Cost (M)`,
                                      text = paste("total project cost is", scales::comma(`Total Cost (M)`), "Million.")))+
  geom_tile()+
  scale_fill_viridis_c(trans="log10", labels=scales::comma)+
  facet_wrap(~`Facet variable`)+
  theme_minimal()+ 
  theme(axis.text.x = element_text(angle = 90, vjust = 1, hjust=1))+
  labs(x=input$x_var,
       y=input$y_var)

  aest::aest_fix_labs(plt)  
})%>%
  bindCache(input$filter_var, input$x_var, input$y_var, input$facet_var)
```

### Table:
  
```{r}
DT::renderDataTable(server=FALSE, {mpi_group_summary()%>%
    DT::datatable(extensions = "Buttons", 
              options = list(rownames = FALSE, 
                             columnDefs = list(list(className = 'dt-center', targets = "_all")),
                             paging = TRUE,
                             scrollX=TRUE,
                             scrollY=TRUE,
                             searching = TRUE,
                             ordering = TRUE,
                             dom = 'Btip',
                             buttons = list(
                                list(extend = 'csv', filename =  "MPI"),
                                list(extend = 'excel', filename = "MPI")
                             ),
                             pageLength=10, 
                             lengthMenu=c(3,5)))
})%>%
  bindCache(input$filter_var, input$x_var, input$y_var, input$facet_var)
```
